name: Convert then commit

on:
  repository_dispatch:
    types: [convert-jsonld]

jobs:
  convert-jsonld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Install jsonld-to-cypher
        run: npm i -g @nissimsan/jsonld-to-cypher@0.0.1
      - name: Run a conversion 
        run: jsonld-to-cypher convert ./docs/vc.jwt  --type jwt
