name: Externally triggered workflow
env: 
  owner: nissimsan
  repo: workflows-spike
on:
  repository_dispatch:
    types: [commit-cypher]
jobs:
  commit-cypher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cbastn/cypher-shell-docker@v1
        with:
          address: ${{ secrets.NEO4J_URI }}
          username: ${{ secrets.NEO4J_USERNAME }}
          password: ${{ secrets.NEO4J_PASSWORD }}
          file: './Sample.cypher'
