name: Push all VCs to Neo
on: [workflow_dispatch]
jobs:
  store-credential:
    runs-on: ubuntu-latest
    name: Store Credential
    steps:
      - name: Get Access Token
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.2
        id: getAccessToken
        with:
          operation-id: getAccessToken
          api-base-url: ${{ secrets.API_BASE_URL }}
          did: ${{ secrets.ORGANIZATION_DID_WEB }}
          token-endpoint: ${{ secrets.TOKEN_ENDPOINT }}
          token-audience: ${{ secrets.TOKEN_AUDIENCE }} 
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Get Credentials
        uses: transmute-industries/verifiable-data-platform-github-action@v0.0.2
        id: getCredentials
        with:
          operation-id: getCredentials

      - name: View Credential
        run: echo "$verifiable_data_platform_api_response" | jq

      - name: Push to Neo
        uses: transmute-industries/jsonld-to-cypher@v0.1.3
        id: merge
        with:
          neo4j-uri: ${{ secrets.NEO4J_URI }}
          neo4j-user: ${{ secrets.NEO4J_USERNAME }}
          neo4j-password: ${{ secrets.NEO4J_PASSWORD }}
          operation: merge
          document: ${{ env.verifiable_data_platform_api_response }}